#include "Import/BlueprintBuilder.h"

#include "Import/AssetImportUtils.h"
#include "CadRobotActor.h"
#include "CadImporterEditor.h"
#include "Components/SceneComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/Blueprint.h"
#include "Engine/SCS_Node.h"
#include "Engine/SimpleConstructionScript.h"
#include "Engine/StaticMesh.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Materials/MaterialInterface.h"
#include "Misc/MessageDialog.h"
#include "Misc/PackageName.h"
#include "PhysicsEngine/PhysicsConstraintComponent.h"
#include "UObject/Package.h"

namespace
{
	constexpr const TCHAR* CadLinkPrefix = TEXT("Link_");
	constexpr const TCHAR* CadVisualPrefix = TEXT("Visual_");
	constexpr const TCHAR* CadJointPrefix = TEXT("Joint_");

	// Convert a package path into an object path usable by LoadObject.
	FString BuildBlueprintObjectPath(const FString& PackagePath)
	{
		const FString AssetName = FPackageName::GetLongPackageAssetName(PackagePath);
		return FString::Printf(TEXT("%s.%s"), *PackagePath, *AssetName);
	}

	// Normalize user-provided names so they are safe as component variable names.
	FString SanitizeComponentName(FString Name)
	{
		Name.ReplaceInline(TEXT(" "), TEXT("_"));
		Name.ReplaceInline(TEXT("-"), TEXT("_"));
		Name.ReplaceInline(TEXT("."), TEXT("_"));
		return Name;
	}

	// Build a deterministic scene-component name for a link node.
	FName BuildLinkComponentName(const FString& LinkName)
	{
		return FName(*FString::Printf(TEXT("%s%s"), CadLinkPrefix, *SanitizeComponentName(LinkName)));
	}

	// Build a deterministic static-mesh component name for a link visual.
	FName BuildVisualComponentName(const FString& LinkName, int32 VisualIndex)
	{
		return FName(*FString::Printf(TEXT("%s%s_%d"), CadVisualPrefix, *SanitizeComponentName(LinkName), VisualIndex));
	}

	// Build a deterministic constraint-component name for a joint definition.
	FName BuildJointComponentName(const FCadImportJoint& Joint)
	{
		FString BaseName = Joint.Name;
		if (BaseName.IsEmpty())
		{
			BaseName = FString::Printf(TEXT("%s_to_%s"), *Joint.Parent, *Joint.Child);
		}

		return FName(*FString::Printf(TEXT("%s%s"), CadJointPrefix, *SanitizeComponentName(BaseName)));
	}

	// Resolve the root scene-component variable name for this import.
	FName BuildRootComponentName(const FString& RootLinkName)
	{
		const FString CandidateName = RootLinkName.IsEmpty() ? TEXT("DefaultSceneRoot") : SanitizeComponentName(RootLinkName);
		return FName(*CandidateName);
	}

	// Parse endpoint selector syntax "LinkName:VisualIndex" into link/index components.
	bool TryParseJointEndpointVisualIndex(const FString& Endpoint, FString& OutLinkName, int32& OutVisualIndex)
	{
		const int32 SeparatorIndex = Endpoint.Find(TEXT(":"), ESearchCase::CaseSensitive, ESearchDir::FromEnd);
		if (SeparatorIndex <= 0 || SeparatorIndex >= Endpoint.Len() - 1)
		{
			return false;
		}

		const FString LinkName = Endpoint.Left(SeparatorIndex).TrimStartAndEnd();
		const FString VisualIndexText = Endpoint.Mid(SeparatorIndex + 1).TrimStartAndEnd();
		int32 VisualIndex = INDEX_NONE;
		if (LinkName.IsEmpty() || !LexTryParseString(VisualIndex, *VisualIndexText) || VisualIndex < 0)
		{
			return false;
		}

		OutLinkName = LinkName;
		OutVisualIndex = VisualIndex;
		return true;
	}

	// Resolve a joint endpoint token to an actual visual component variable name.
	FName ResolveJointEndpointComponentName(const FString& Endpoint, const TMap<FString, TArray<FName>>& VisualComponentNamesByLink)
	{
		if (Endpoint.IsEmpty())
		{
			return NAME_None;
		}

		// Backward-compatible default: endpoint is a link name and resolves to its primary visual.
		if (const TArray<FName>* VisualNames = VisualComponentNamesByLink.Find(Endpoint))
		{
			if (!VisualNames->IsEmpty())
			{
				return (*VisualNames)[0];
			}
		}

		// Optional explicit selector format: "LinkName:VisualIndex".
		FString IndexedLinkName;
		int32 IndexedVisual = INDEX_NONE;
		if (TryParseJointEndpointVisualIndex(Endpoint, IndexedLinkName, IndexedVisual))
		{
			if (const TArray<FName>* VisualNames = VisualComponentNamesByLink.Find(IndexedLinkName))
			{
				if (VisualNames->IsValidIndex(IndexedVisual))
				{
					return (*VisualNames)[IndexedVisual];
				}
			}
		}

		// Optional explicit selector format: actual component variable name.
		const FName ExplicitComponentName(*Endpoint);
		for (const TPair<FString, TArray<FName>>& Pair : VisualComponentNamesByLink)
		{
			if (Pair.Value.Contains(ExplicitComponentName))
			{
				return ExplicitComponentName;
			}
		}

		return NAME_None;
	}

	// Identify SCS nodes that were generated by this importer and can be replaced.
	bool IsCadGeneratedNode(const USCS_Node* Node)
	{
		if (!Node)
		{
			return false;
		}

		const FString VariableName = Node->GetVariableName().ToString();
		return VariableName.StartsWith(CadLinkPrefix)
			|| VariableName.StartsWith(CadVisualPrefix)
			|| VariableName.StartsWith(CadJointPrefix)
			|| VariableName.StartsWith(TEXT("SM_"));
	}

	// Return an existing default root node or create one when missing.
	USCS_Node* EnsureRootNode(USimpleConstructionScript* SCS, const FName DesiredRootName)
	{
		if (!SCS)
		{
			return nullptr;
		}

		const FName RootName = DesiredRootName.IsNone() ? FName(TEXT("DefaultSceneRoot")) : DesiredRootName;

		if (USCS_Node* ExistingRoot = SCS->GetDefaultSceneRootNode())
		{
			if (ExistingRoot->GetVariableName() != RootName)
			{
				ExistingRoot->SetVariableName(RootName);
			}
			return ExistingRoot;
		}

		USCS_Node* RootNode = SCS->CreateNode(USceneComponent::StaticClass(), RootName);
		if (!RootNode)
		{
			return nullptr;
		}

		SCS->AddNode(RootNode);
		return RootNode;
	}

	// DFS helper that checks whether a constraint path already exists between components.
	bool HasConstraintPathRecursive(
		const FName& Current,
		const FName& Target,
		const TMap<FName, TArray<FName>>& Adjacency,
		TSet<FName>& InOutVisited)
	{
		if (Current.IsNone())
		{
			return false;
		}

		if (Current == Target)
		{
			return true;
		}

		if (InOutVisited.Contains(Current))
		{
			return false;
		}
		InOutVisited.Add(Current);

		const TArray<FName>* Neighbors = Adjacency.Find(Current);
		if (!Neighbors)
		{
			return false;
		}

		for (const FName& Next : *Neighbors)
		{
			if (HasConstraintPathRecursive(Next, Target, Adjacency, InOutVisited))
			{
				return true;
			}
		}

		return false;
	}

	// Guard against over-constraining by rejecting constraints that would introduce loops.
	bool WouldCreateConstraintLoop(
		const FName& ComponentA,
		const FName& ComponentB,
		const TMap<FName, TArray<FName>>& Adjacency)
	{
		if (ComponentA.IsNone() || ComponentB.IsNone())
		{
			return false;
		}

		if (ComponentA == ComponentB)
		{
			return true;
		}

		TSet<FName> Visited;
		return HasConstraintPathRecursive(ComponentA, ComponentB, Adjacency, Visited);
	}

	// Record a bidirectional adjacency edge for a newly added constraint pair.
	void AddConstraintEdge(
		const FName& ComponentA,
		const FName& ComponentB,
		TMap<FName, TArray<FName>>& Adjacency)
	{
		if (ComponentA.IsNone() || ComponentB.IsNone() || ComponentA == ComponentB)
		{
			return;
		}

		TArray<FName>& AList = Adjacency.FindOrAdd(ComponentA);
		if (!AList.Contains(ComponentB))
		{
			AList.Add(ComponentB);
		}

		TArray<FName>& BList = Adjacency.FindOrAdd(ComponentB);
		if (!BList.Contains(ComponentA))
		{
			BList.Add(ComponentA);
		}
	}

	// Reset a constraint to fully locked translational/rotational motion.
	void ConfigureFixedConstraint(UPhysicsConstraintComponent& ConstraintComponent)
	{
		ConstraintComponent.ConstraintInstance.ProfileInstance.bDisableCollision = true;
		ConstraintComponent.ConstraintInstance.SetLinearXLimit(ELinearConstraintMotion::LCM_Locked, 0.0f);
		ConstraintComponent.ConstraintInstance.SetLinearYLimit(ELinearConstraintMotion::LCM_Locked, 0.0f);
		ConstraintComponent.ConstraintInstance.SetLinearZLimit(ELinearConstraintMotion::LCM_Locked, 0.0f);
		ConstraintComponent.ConstraintInstance.SetAngularSwing1Limit(EAngularConstraintMotion::ACM_Locked, 0.0f);
		ConstraintComponent.ConstraintInstance.SetAngularSwing2Limit(EAngularConstraintMotion::ACM_Locked, 0.0f);
		ConstraintComponent.ConstraintInstance.SetAngularTwistLimit(EAngularConstraintMotion::ACM_Locked, 0.0f);
	}

	enum class ECadAngularDriveAxis : uint8
	{
		Twist,
		Swing1,
		Swing2
	};

	enum class ECadLinearDriveAxis : uint8
	{
		X,
		Y,
		Z
	};

	// Pick the dominant axis in constraint local space for revolute motion setup.
	ECadAngularDriveAxis GetDominantAngularAxis(const FVector& Axis)
	{
		const FVector SafeAxis = Axis.GetSafeNormal();
		const FVector AbsAxis(FMath::Abs(SafeAxis.X), FMath::Abs(SafeAxis.Y), FMath::Abs(SafeAxis.Z));

		if (AbsAxis.X >= AbsAxis.Y && AbsAxis.X >= AbsAxis.Z)
		{
			return ECadAngularDriveAxis::Twist;
		}

		return (AbsAxis.Y >= AbsAxis.Z) ? ECadAngularDriveAxis::Swing2 : ECadAngularDriveAxis::Swing1;
	}

	// Pick the dominant axis in constraint local space for prismatic motion setup.
	ECadLinearDriveAxis GetDominantLinearAxis(const FVector& Axis)
	{
		const FVector SafeAxis = Axis.GetSafeNormal();
		const FVector AbsAxis(FMath::Abs(SafeAxis.X), FMath::Abs(SafeAxis.Y), FMath::Abs(SafeAxis.Z));

		if (AbsAxis.X >= AbsAxis.Y && AbsAxis.X >= AbsAxis.Z)
		{
			return ECadLinearDriveAxis::X;
		}

		return (AbsAxis.Y >= AbsAxis.Z) ? ECadLinearDriveAxis::Y : ECadLinearDriveAxis::Z;
	}

	// Resolve whether motor drive should be enabled from explicit joint drive or profile defaults.
	bool ResolveJointDriveEnabled(const ECadImportModelProfile Profile, const FCadImportJoint& Joint)
	{
		if (Joint.Drive.bHasDrive)
		{
			return Joint.Drive.bEnabled;
		}

		return Profile == ECadImportModelProfile::DynamicRobot;
	}

	// Configure fixed/revolute/prismatic limits and drive parameters on a constraint template.
	void ConfigureJointConstraint(UPhysicsConstraintComponent& ConstraintComponent, const FCadImportJoint& Joint, const ECadImportModelProfile Profile)
	{
		// Start from fully locked and open only the axis specified by the JSON joint.
		ConfigureFixedConstraint(ConstraintComponent);
		if (Joint.Type == ECadImportJointType::Fixed)
		{
			return;
		}

		if (Joint.Type == ECadImportJointType::Revolute)
		{
			const ECadAngularDriveAxis DriveAxis = GetDominantAngularAxis(Joint.Axis);
			const bool bHasUsableLimit = Joint.Limit.bHasLimit && !FMath::IsNearlyEqual(Joint.Limit.Lower, Joint.Limit.Upper, KINDA_SMALL_NUMBER);
			const float LimitSpanDegrees = FMath::Abs(Joint.Limit.Upper - Joint.Limit.Lower);
			const bool bTreatAsUnlimitedRotation = bHasUsableLimit && LimitSpanDegrees > 360.0f;
			const float SymmetricLimitDegrees = (bHasUsableLimit && !bTreatAsUnlimitedRotation)
				? FMath::Max(FMath::Abs(Joint.Limit.Lower), FMath::Abs(Joint.Limit.Upper))
				: 0.0f;
			const EAngularConstraintMotion AngularMotion = (bHasUsableLimit && !bTreatAsUnlimitedRotation)
				? EAngularConstraintMotion::ACM_Limited
				: EAngularConstraintMotion::ACM_Free;

			switch (DriveAxis)
			{
			case ECadAngularDriveAxis::Twist:
				ConstraintComponent.ConstraintInstance.SetAngularTwistLimit(AngularMotion, SymmetricLimitDegrees);
				break;
			case ECadAngularDriveAxis::Swing1:
				ConstraintComponent.ConstraintInstance.SetAngularSwing1Limit(AngularMotion, SymmetricLimitDegrees);
				break;
			case ECadAngularDriveAxis::Swing2:
				ConstraintComponent.ConstraintInstance.SetAngularSwing2Limit(AngularMotion, SymmetricLimitDegrees);
				break;
			default:
				break;
			}

			if (!ResolveJointDriveEnabled(Profile, Joint))
			{
				return;
			}

			// Configure an angular motor using Twist+Swing drives (not SLERP).
			ConstraintComponent.SetAngularDriveMode(EAngularDriveMode::TwistAndSwing);
			ConstraintComponent.SetOrientationDriveSLERP(false);
			ConstraintComponent.SetAngularVelocityDriveSLERP(false);

			const bool bEnableTwistDrive = (DriveAxis == ECadAngularDriveAxis::Twist);
			const bool bEnableSwingDrive = (DriveAxis == ECadAngularDriveAxis::Swing1 || DriveAxis == ECadAngularDriveAxis::Swing2);
			bool bEnableOrientationDrive = true;
			bool bEnableVelocityDrive = true;
			if (Joint.Drive.bHasDrive)
			{
				switch (Joint.Drive.Mode)
				{
				case ECadImportJointDriveMode::None:
					return;
				case ECadImportJointDriveMode::Velocity:
					bEnableOrientationDrive = false;
					bEnableVelocityDrive = true;
					break;
				case ECadImportJointDriveMode::Position:
					bEnableOrientationDrive = true;
					bEnableVelocityDrive = true;
					break;
				default:
					break;
				}
			}

			ConstraintComponent.SetOrientationDriveTwistAndSwing(
				bEnableOrientationDrive && bEnableTwistDrive,
				bEnableOrientationDrive && bEnableSwingDrive);
			ConstraintComponent.SetAngularVelocityDriveTwistAndSwing(
				bEnableVelocityDrive && bEnableTwistDrive,
				bEnableVelocityDrive && bEnableSwingDrive);

			constexpr float DefaultAngularMotorStrength = 1000.0f;
			constexpr float DefaultAngularMotorDamping = DefaultAngularMotorStrength * 2.0f;
			const float AngularMotorStrength = Joint.Drive.bHasDrive ? Joint.Drive.Strength : DefaultAngularMotorStrength;
			const float AngularMotorDamping = Joint.Drive.bHasDrive ? Joint.Drive.Damping : DefaultAngularMotorDamping;
			const float AngularMotorMaxForce = Joint.Drive.bHasDrive ? Joint.Drive.MaxForce : 0.0f;
			ConstraintComponent.SetAngularDriveParams(AngularMotorStrength, AngularMotorDamping, AngularMotorMaxForce);

			// JSON currently provides joint limits, not commanded joint angles. Hold the authored zero offset by default.
			ConstraintComponent.SetAngularOrientationTarget(FRotator::ZeroRotator);

			FVector AngularVelocityTarget = FVector::ZeroVector;
			if (bEnableVelocityDrive && Joint.Limit.bHasLimit && FMath::Abs(Joint.Limit.Velocity) > KINDA_SMALL_NUMBER)
			{
				const float TargetSpeedDegrees = FMath::Abs(Joint.Limit.Velocity);
				switch (DriveAxis)
				{
				case ECadAngularDriveAxis::Twist:
					AngularVelocityTarget = FVector(TargetSpeedDegrees, 0.0f, 0.0f);
					break;
				case ECadAngularDriveAxis::Swing1:
					AngularVelocityTarget = FVector(0.0f, TargetSpeedDegrees, 0.0f);
					break;
				case ECadAngularDriveAxis::Swing2:
					AngularVelocityTarget = FVector(0.0f, 0.0f, TargetSpeedDegrees);
					break;
				default:
					break;
				}
			}
			ConstraintComponent.SetAngularVelocityTarget(AngularVelocityTarget);
			return;
		}

		if (Joint.Type == ECadImportJointType::Prismatic)
		{
			const ECadLinearDriveAxis DriveAxis = GetDominantLinearAxis(Joint.Axis);
			const bool bHasUsableLimit = Joint.Limit.bHasLimit && !FMath::IsNearlyEqual(Joint.Limit.Lower, Joint.Limit.Upper, KINDA_SMALL_NUMBER);
			const float SymmetricLimit = bHasUsableLimit
				? FMath::Max(FMath::Abs(Joint.Limit.Lower), FMath::Abs(Joint.Limit.Upper))
				: 0.0f;
			const ELinearConstraintMotion LinearMotion = bHasUsableLimit
				? ELinearConstraintMotion::LCM_Limited
				: ELinearConstraintMotion::LCM_Free;

			switch (DriveAxis)
			{
			case ECadLinearDriveAxis::X:
				ConstraintComponent.ConstraintInstance.SetLinearXLimit(LinearMotion, SymmetricLimit);
				break;
			case ECadLinearDriveAxis::Y:
				ConstraintComponent.ConstraintInstance.SetLinearYLimit(LinearMotion, SymmetricLimit);
				break;
			case ECadLinearDriveAxis::Z:
				ConstraintComponent.ConstraintInstance.SetLinearZLimit(LinearMotion, SymmetricLimit);
				break;
			default:
				break;
			}

			if (!ResolveJointDriveEnabled(Profile, Joint))
			{
				return;
			}

			const bool bDriveX = (DriveAxis == ECadLinearDriveAxis::X);
			const bool bDriveY = (DriveAxis == ECadLinearDriveAxis::Y);
			const bool bDriveZ = (DriveAxis == ECadLinearDriveAxis::Z);

			bool bEnablePositionDrive = true;
			bool bEnableVelocityDrive = true;
			if (Joint.Drive.bHasDrive)
			{
				switch (Joint.Drive.Mode)
				{
				case ECadImportJointDriveMode::None:
					return;
				case ECadImportJointDriveMode::Velocity:
					bEnablePositionDrive = false;
					bEnableVelocityDrive = true;
					break;
				case ECadImportJointDriveMode::Position:
					bEnablePositionDrive = true;
					bEnableVelocityDrive = true;
					break;
				default:
					break;
				}
			}

			ConstraintComponent.SetLinearPositionDrive(
				bEnablePositionDrive && bDriveX,
				bEnablePositionDrive && bDriveY,
				bEnablePositionDrive && bDriveZ);
			ConstraintComponent.SetLinearVelocityDrive(
				bEnableVelocityDrive && bDriveX,
				bEnableVelocityDrive && bDriveY,
				bEnableVelocityDrive && bDriveZ);

			constexpr float DefaultLinearMotorStrength = 1000.0f;
			constexpr float DefaultLinearMotorDamping = DefaultLinearMotorStrength * 2.0f;
			const float LinearMotorStrength = Joint.Drive.bHasDrive ? Joint.Drive.Strength : DefaultLinearMotorStrength;
			const float LinearMotorDamping = Joint.Drive.bHasDrive ? Joint.Drive.Damping : DefaultLinearMotorDamping;
			const float LinearMotorMaxForce = Joint.Drive.bHasDrive ? Joint.Drive.MaxForce : 0.0f;
			ConstraintComponent.SetLinearDriveParams(LinearMotorStrength, LinearMotorDamping, LinearMotorMaxForce);
			ConstraintComponent.SetLinearPositionTarget(FVector::ZeroVector);

			FVector LinearVelocityTarget = FVector::ZeroVector;
			if (bEnableVelocityDrive && Joint.Limit.bHasLimit && FMath::Abs(Joint.Limit.Velocity) > KINDA_SMALL_NUMBER)
			{
				const float TargetSpeed = FMath::Abs(Joint.Limit.Velocity);
				switch (DriveAxis)
				{
				case ECadLinearDriveAxis::X:
					LinearVelocityTarget = FVector(TargetSpeed, 0.0f, 0.0f);
					break;
				case ECadLinearDriveAxis::Y:
					LinearVelocityTarget = FVector(0.0f, TargetSpeed, 0.0f);
					break;
				case ECadLinearDriveAxis::Z:
					LinearVelocityTarget = FVector(0.0f, 0.0f, TargetSpeed);
					break;
				default:
					break;
				}
			}
			ConstraintComponent.SetLinearVelocityTarget(LinearVelocityTarget);
		}
	}

	// Persist root placement metadata onto the generated robot blueprint CDO hint.
	void ApplyRootPlacementHintToBlueprint(UBlueprint* Blueprint, const FCadImportModel& Model)
	{
		if (!Blueprint || !Blueprint->GeneratedClass)
		{
			return;
		}

		ACadRobotActor* RobotDefaultObject = Cast<ACadRobotActor>(Blueprint->GeneratedClass->GetDefaultObject());
		if (!RobotDefaultObject)
		{
			return;
		}

		RobotDefaultObject->ImportRootPlacementHint.bHasWorldTransform = Model.RootPlacement.bHasWorldTransform;
		RobotDefaultObject->ImportRootPlacementHint.WorldLocation = Model.RootPlacement.WorldTransform.GetLocation();
		RobotDefaultObject->ImportRootPlacementHint.WorldRotation = Model.RootPlacement.WorldTransform.Rotator();
		RobotDefaultObject->ImportRootPlacementHint.WorldScale = Model.RootPlacement.WorldTransform.GetScale3D();
		RobotDefaultObject->ImportRootPlacementHint.ParentActorName = Model.RootPlacement.ParentActorName;
	}

	// Create UPhysicsConstraintComponent SCS nodes for each joint, attaching them under the
	// child link's SCS node. Skips fixed-assembly profiles (handled by the caller).
	bool BuildJointConstraintComponents(
		USimpleConstructionScript* SCS,
		const FCadImportModel& Model,
		const FString& BaseLinkName,
		const TMap<FString, USCS_Node*>& LinkNodeByName,
		const TMap<FString, FTransform>& LinkTransformByName,
		const TMap<FString, FTransform>& RelativeTransformByChild,
		const TMap<FString, TArray<FName>>& VisualComponentNamesByLink,
		const TMap<FName, FTransform>& VisualTransformByComponentName,
		const TMap<FName, FString>& VisualOwningLinkByComponentName,
		int32& OutWorldAnchorFallbackCount,
		FString& OutError)
	{
		OutWorldAnchorFallbackCount = 0;
		TMap<FName, TArray<FName>> ConstraintAdjacency;

		for (int32 JointIndex = 0; JointIndex < Model.Joints.Num(); ++JointIndex)
		{
			const FCadImportJoint& Joint = Model.Joints[JointIndex];
			if (Joint.Child.IsEmpty())
			{
				continue;
			}

			USCS_Node* const* ChildLinkNodePtr = LinkNodeByName.Find(Joint.Child);
			if (!ChildLinkNodePtr || !(*ChildLinkNodePtr))
			{
				UE_LOG(LogCadImporter, Warning, TEXT("Skipping joint component for %s because child link node was not found."), *Joint.Name);
				continue;
			}

			const FString EndpointName1 = Joint.ComponentName1.IsEmpty() ? Joint.Parent : Joint.ComponentName1;
			const FString EndpointName2 = Joint.ComponentName2.IsEmpty() ? Joint.Child : Joint.ComponentName2;
			const FName ComponentName1 = ResolveJointEndpointComponentName(EndpointName1, VisualComponentNamesByLink);
			const FName ComponentName2 = ResolveJointEndpointComponentName(EndpointName2, VisualComponentNamesByLink);
			const bool bIsRootEndpointWithoutVisual = !BaseLinkName.IsEmpty()
				&& Joint.Parent == BaseLinkName
				&& !VisualComponentNamesByLink.Contains(BaseLinkName);
			const bool bAllowWorldAnchorForComponent1 = bIsRootEndpointWithoutVisual && ComponentName1.IsNone();

			if ((!bAllowWorldAnchorForComponent1 && ComponentName1.IsNone()) || ComponentName2.IsNone())
			{
				UE_LOG(LogCadImporter, Warning,
					TEXT("Skipping joint %s because endpoints could not be resolved (component_name1=%s component_name2=%s parent=%s child=%s). Expected link name, LinkName:VisualIndex, or explicit visual component name."),
					*Joint.Name, *Joint.ComponentName1, *Joint.ComponentName2, *Joint.Parent, *Joint.Child);
				continue;
			}

			if (bAllowWorldAnchorForComponent1)
			{
				++OutWorldAnchorFallbackCount;
				UE_LOG(LogCadImporter, Display,
					TEXT("Joint %s uses world anchor for component_name1 because root link '%s' has no visuals."),
					*Joint.Name,
					*BaseLinkName);
			}

			if (WouldCreateConstraintLoop(ComponentName1, ComponentName2, ConstraintAdjacency))
			{
				UE_LOG(LogCadImporter, Warning, TEXT("Skipping joint %s (%s <-> %s) because it would create a constraint loop."),
					*Joint.Name, *ComponentName1.ToString(), *ComponentName2.ToString());
				continue;
			}

			FTransform JointFrameInParentLink = Joint.Transform;
			if (const FTransform* RelativeJoint = RelativeTransformByChild.Find(Joint.Child))
			{
				JointFrameInParentLink = *RelativeJoint;
			}
			else if (const FTransform* ChildLinkTransform = LinkTransformByName.Find(Joint.Child))
			{
				JointFrameInParentLink = *ChildLinkTransform;
			}
			const FTransform JointFrameInChildLink = FTransform::Identity;

			const auto ResolveEndpointOwningLink = [&](const FString& EndpointName, const FName& ComponentName, const FString& FallbackLinkName) -> FString
			{
				if (const FString* OwningLink = VisualOwningLinkByComponentName.Find(ComponentName))
				{
					return *OwningLink;
				}

				FString ParsedLinkName;
				int32 ParsedVisualIndex = INDEX_NONE;
				if (TryParseJointEndpointVisualIndex(EndpointName, ParsedLinkName, ParsedVisualIndex))
				{
					return ParsedLinkName;
				}

				if (VisualComponentNamesByLink.Contains(EndpointName))
				{
					return EndpointName;
				}

				return FallbackLinkName;
			};

			const FString EndpointLink1 = ResolveEndpointOwningLink(EndpointName1, ComponentName1, Joint.Parent);
			const FString EndpointLink2 = ResolveEndpointOwningLink(EndpointName2, ComponentName2, Joint.Child);

			const auto ResolveJointFrameInLink = [&](const FString& LinkName) -> FTransform
			{
				if (!Joint.Parent.IsEmpty() && LinkName == Joint.Parent)
				{
					return JointFrameInParentLink;
				}
				if (!Joint.Child.IsEmpty() && LinkName == Joint.Child)
				{
					return JointFrameInChildLink;
				}
				return FTransform::Identity;
			};

			const auto BuildConstraintLocalFrame = [&](const FName& ComponentName, const FString& EndpointLinkName) -> FTransform
			{
				const FTransform JointFrameInLink = ResolveJointFrameInLink(EndpointLinkName);
				if (ComponentName.IsNone())
				{
					// ComponentName=None means world anchor; use the constraint component origin.
					return FTransform::Identity;
				}

				if (const FTransform* ComponentInLink = VisualTransformByComponentName.Find(ComponentName))
				{
					// Joint transforms in JSON are link-relative. Convert to component-local
					// so constraint pivots stay on link frames instead of mesh pivot centers.
					return JointFrameInLink.GetRelativeTransform(*ComponentInLink);
				}

				return JointFrameInLink;
			};

			const FTransform ComponentFrame1 = BuildConstraintLocalFrame(ComponentName1, EndpointLink1);
			const FTransform ComponentFrame2 = BuildConstraintLocalFrame(ComponentName2, EndpointLink2);

			USCS_Node* JointNode = SCS->CreateNode(UPhysicsConstraintComponent::StaticClass(), BuildJointComponentName(Joint));
			if (!JointNode || !JointNode->ComponentTemplate)
			{
				OutError = FString::Printf(TEXT("Failed to create physics constraint component for joint: %s"), *Joint.Name);
				return false;
			}

			if (UPhysicsConstraintComponent* ConstraintTemplate = Cast<UPhysicsConstraintComponent>(JointNode->ComponentTemplate))
			{
				ConstraintTemplate->SetRelativeTransform(FTransform::Identity);
				ConstraintTemplate->ComponentName1.ComponentName = ComponentName1;
				ConstraintTemplate->ComponentName2.ComponentName = ComponentName2;
				ConstraintTemplate->SetConstraintReferenceFrame(EConstraintFrame::Frame1, ComponentFrame1);
				ConstraintTemplate->SetConstraintReferenceFrame(EConstraintFrame::Frame2, ComponentFrame2);
				ConfigureJointConstraint(*ConstraintTemplate, Joint, Model.Profile);
			}

			(*ChildLinkNodePtr)->AddChildNode(JointNode);
			AddConstraintEdge(ComponentName1, ComponentName2, ConstraintAdjacency);
		}

		return true;
	}
}

UBlueprint* FCadBlueprintBuilder::BuildBlueprint(
	const FCadImportModel& Model,
	const FCadImportPaths& Paths,
	const FCadImportResult& ImportResult,
	FString& OutError)
{
	if (Paths.BlueprintPath.IsEmpty())
	{
		OutError = TEXT("Blueprint path is empty.");
		return nullptr;
	}

	const FString ObjectPath = BuildBlueprintObjectPath(Paths.BlueprintPath);
	UBlueprint* Blueprint = LoadObject<UBlueprint>(nullptr, *ObjectPath);

	if (!Blueprint)
	{
		const FString AssetName = FPackageName::GetLongPackageAssetName(Paths.BlueprintPath);
		if (AssetName.IsEmpty())
		{
			OutError = FString::Printf(TEXT("Invalid blueprint package path: %s"), *Paths.BlueprintPath);
			return nullptr;
		}

		UPackage* Package = CreatePackage(*Paths.BlueprintPath);
		if (!Package)
		{
			OutError = FString::Printf(TEXT("Failed to create package: %s"), *Paths.BlueprintPath);
			return nullptr;
		}

		Blueprint = FKismetEditorUtilities::CreateBlueprint(
			ACadRobotActor::StaticClass(),
			Package,
			FName(*AssetName),
			BPTYPE_Normal,
			UBlueprint::StaticClass(),
			UBlueprintGeneratedClass::StaticClass(),
			FName(TEXT("CadImporter")));
		if (!Blueprint)
		{
			OutError = FString::Printf(TEXT("Failed to create blueprint asset: %s"), *Paths.BlueprintPath);
			return nullptr;
		}

		UE_LOG(LogCadImporter, Display, TEXT("Created robot blueprint: %s"), *ObjectPath);
	}
	else if (Blueprint->ParentClass != ACadRobotActor::StaticClass())
	{
		Blueprint->ParentClass = ACadRobotActor::StaticClass();
		FBlueprintEditorUtils::RefreshAllNodes(Blueprint);
		UE_LOG(LogCadImporter, Display, TEXT("Reparented robot blueprint to ACadRobotActor: %s"), *ObjectPath);
	}

	if (!BuildComponents(Blueprint, Model, ImportResult, OutError))
	{
		return nullptr;
	}

	FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified(Blueprint);
	FKismetEditorUtilities::CompileBlueprint(Blueprint);
	ApplyRootPlacementHintToBlueprint(Blueprint, Model);
	Blueprint->MarkPackageDirty();
	return Blueprint;
}

bool FCadBlueprintBuilder::BuildComponents(
	UBlueprint* Blueprint,
	const FCadImportModel& Model,
	const FCadImportResult& ImportResult,
	FString& OutError)
{
	if (!Blueprint || !Blueprint->SimpleConstructionScript)
	{
		OutError = TEXT("Blueprint has no SimpleConstructionScript.");
		return false;
	}

	const bool bIsFixedAssembly = (Model.Profile == ECadImportModelProfile::FixedAssembly);
	const bool bUseFlatLinkHierarchy = !bIsFixedAssembly;

	FString BaseLinkName = Model.RootLinkName;
	if (BaseLinkName.IsEmpty() && Model.Links.Num() > 0)
	{
		BaseLinkName = Model.Links[0].Name;
	}

	USimpleConstructionScript* SCS = Blueprint->SimpleConstructionScript;
	USCS_Node* RootNode = EnsureRootNode(
		SCS,
		bUseFlatLinkHierarchy ? FName(TEXT("DefaultSceneRoot")) : BuildRootComponentName(BaseLinkName));
	if (!RootNode)
	{
		OutError = TEXT("Failed to create/find root scene node.");
		return false;
	}

	TArray<USCS_Node*> ExistingNodes = SCS->GetAllNodes();
	TArray<USCS_Node*> NodesToRemove;
	for (USCS_Node* ExistingNode : ExistingNodes)
	{
		if (!ExistingNode || ExistingNode == RootNode)
		{
			continue;
		}

		if (IsCadGeneratedNode(ExistingNode))
		{
			NodesToRemove.Add(ExistingNode);
		}
	}

	for (USCS_Node* NodeToRemove : NodesToRemove)
	{
		SCS->RemoveNode(NodeToRemove);
	}

	TMap<FString, FString> ParentByChild;
	TMap<FString, FTransform> RelativeTransformByChild;
	TMap<FString, FTransform> LinkTransformByName;
	for (const FCadImportLink& Link : Model.Links)
	{
		LinkTransformByName.Add(Link.Name, Link.Transform);
	}

	for (const FCadImportJoint& Joint : Model.Joints)
	{
		if (!Joint.Parent.IsEmpty() && !Joint.Child.IsEmpty())
		{
			if (!ParentByChild.Contains(Joint.Child))
			{
				ParentByChild.Add(Joint.Child, Joint.Parent);
			}
			if (!RelativeTransformByChild.Contains(Joint.Child))
			{
				RelativeTransformByChild.Add(Joint.Child, Joint.Transform);
			}
		}
	}

	TMap<FString, USCS_Node*> LinkNodeByName;
	TMap<FString, USCS_Node*> PrimaryVisualNodeByLink;
	TMap<FString, int32> PrimaryVisualIndexByLink;
	TMap<FString, TArray<FName>> VisualComponentNamesByLink;
	TMap<FName, FTransform> VisualTransformByComponentName;
	TMap<FName, FString> VisualOwningLinkByComponentName;

	for (const FCadImportLink& Link : Model.Links)
	{
		if (!bUseFlatLinkHierarchy && !BaseLinkName.IsEmpty() && Link.Name == BaseLinkName)
		{
			// Root link should be represented by the SCS root node itself.
			LinkNodeByName.Add(Link.Name, RootNode);
			continue;
		}

		USCS_Node* LinkNode = SCS->CreateNode(USceneComponent::StaticClass(), BuildLinkComponentName(Link.Name));
		if (!LinkNode || !LinkNode->ComponentTemplate)
		{
			OutError = FString::Printf(TEXT("Failed to create SceneComponent node for link: %s"), *Link.Name);
			return false;
		}

		LinkNodeByName.Add(Link.Name, LinkNode);
	}

	for (const FCadImportLink& Link : Model.Links)
	{
		USCS_Node** LinkNodePtr = LinkNodeByName.Find(Link.Name);
		if (!LinkNodePtr || !(*LinkNodePtr))
		{
			continue;
		}

		const bool bIsBaseLink = (!BaseLinkName.IsEmpty() && Link.Name == BaseLinkName);
		USCS_Node* ParentNode = RootNode;
		if (!bUseFlatLinkHierarchy && !bIsBaseLink)
		{
			if (const FString* ParentLinkName = ParentByChild.Find(Link.Name))
			{
				if (USCS_Node** ParentLinkNode = LinkNodeByName.Find(*ParentLinkName))
				{
					ParentNode = *ParentLinkNode;
				}
			}
		}

		if (bUseFlatLinkHierarchy || !bIsBaseLink)
		{
			ParentNode->AddChildNode(*LinkNodePtr);
		}

		FTransform RelativeTransform = FTransform::Identity;
		if (bUseFlatLinkHierarchy)
		{
			if (const FTransform* LinkTransform = LinkTransformByName.Find(Link.Name))
			{
				RelativeTransform = *LinkTransform;
			}
		}
		else if (!bIsBaseLink)
		{
			if (const FTransform* JointTransform = RelativeTransformByChild.Find(Link.Name))
			{
				RelativeTransform = *JointTransform;
			}
			else if (const FTransform* LinkTransform = LinkTransformByName.Find(Link.Name))
			{
				RelativeTransform = *LinkTransform;
			}
		}

		if (USceneComponent* LinkTemplate = Cast<USceneComponent>((*LinkNodePtr)->ComponentTemplate))
		{
			LinkTemplate->SetRelativeTransform(RelativeTransform);
			LinkTemplate->SetMobility(bIsFixedAssembly ? EComponentMobility::Static : EComponentMobility::Movable);
		}
	}

	for (const FCadImportLink& Link : Model.Links)
	{
		USCS_Node** LinkNodePtr = LinkNodeByName.Find(Link.Name);
		if (!LinkNodePtr || !(*LinkNodePtr))
		{
			continue;
		}

		const TArray<FString>* MeshPaths = ImportResult.MeshAssetsByLink.Find(Link.Name);
		if (!MeshPaths || MeshPaths->Num() == 0)
		{
			UE_LOG(LogCadImporter, Warning, TEXT("No imported visual meshes mapped for link: %s"), *Link.Name);
			continue;
		}

		for (int32 VisualIndex = 0; VisualIndex < MeshPaths->Num(); ++VisualIndex)
		{
			const FString& MeshPath = (*MeshPaths)[VisualIndex];
			if (MeshPath.IsEmpty())
			{
				continue;
			}

			const FString MeshObjectPath = CadAssetImportUtils::PackagePathToObjectPath(MeshPath);
			UStaticMesh* StaticMesh = LoadObject<UStaticMesh>(nullptr, *MeshObjectPath);
			if (!StaticMesh)
			{
				UE_LOG(LogCadImporter, Warning, TEXT("Failed to load visual mesh for link %s: %s"), *Link.Name, *MeshPath);
				continue;
			}

			USCS_Node* VisualNode = SCS->CreateNode(UStaticMeshComponent::StaticClass(), BuildVisualComponentName(Link.Name, VisualIndex));
			if (!VisualNode || !VisualNode->ComponentTemplate)
			{
				OutError = FString::Printf(TEXT("Failed to create visual component for link: %s"), *Link.Name);
				return false;
			}

			const bool bIsPrimaryVisual = !PrimaryVisualNodeByLink.Contains(Link.Name);
			const bool bAttachUnderPrimaryVisual = !bIsPrimaryVisual;
			const FCadImportVisual* VisualDefinition = Link.Visuals.IsValidIndex(VisualIndex) ? &Link.Visuals[VisualIndex] : nullptr;
			const int32 PrimaryVisualIndex = PrimaryVisualIndexByLink.FindRef(Link.Name);
			const FCadImportVisual* PrimaryVisualDefinition = Link.Visuals.IsValidIndex(PrimaryVisualIndex) ? &Link.Visuals[PrimaryVisualIndex] : nullptr;
			FTransform RelativeVisualTransform = VisualDefinition ? VisualDefinition->Transform : FTransform::Identity;
			if (bAttachUnderPrimaryVisual && VisualDefinition && PrimaryVisualDefinition)
			{
				// JSON visual transforms are link-relative. If this visual is parented under the primary visual,
				// convert it into primary-visual-relative space before assigning the SCS relative transform.
				RelativeVisualTransform = VisualDefinition->Transform.GetRelativeTransform(PrimaryVisualDefinition->Transform);

				// Explicitly preserve relative scale when attaching under primary visual.
				const FVector ParentScale = PrimaryVisualDefinition->Transform.GetScale3D();
				const FVector ChildScale = VisualDefinition->Transform.GetScale3D();
				auto ComputeRelativeScale = [](const float ChildAxisScale, const float ParentAxisScale) -> float
				{
					return !FMath::IsNearlyZero(ParentAxisScale)
						? (ChildAxisScale / ParentAxisScale)
						: ChildAxisScale;
				};
				RelativeVisualTransform.SetScale3D(FVector(
					ComputeRelativeScale(ChildScale.X, ParentScale.X),
					ComputeRelativeScale(ChildScale.Y, ParentScale.Y),
					ComputeRelativeScale(ChildScale.Z, ParentScale.Z)));
			}

			if (UStaticMeshComponent* VisualTemplate = Cast<UStaticMeshComponent>(VisualNode->ComponentTemplate))
			{
				const bool bIsBaseLink = (!BaseLinkName.IsEmpty() && Link.Name == BaseLinkName);

				VisualTemplate->SetStaticMesh(StaticMesh);
				// TODO(builder): add an overlap-handling policy when actors/components collapse onto
				// the same attachment path with identical transforms during import.
				VisualTemplate->SetRelativeTransform(RelativeVisualTransform);
				VisualTemplate->SetMobility(bIsFixedAssembly ? EComponentMobility::Static : EComponentMobility::Movable);
				VisualTemplate->SetEnableGravity(false);
				VisualTemplate->SetPhysicsMaxAngularVelocityInDegrees(180.0f);

				if (VisualDefinition && !VisualDefinition->MaterialPath.IsEmpty())
				{
					const FString MaterialObjectPath = CadAssetImportUtils::PackagePathToObjectPath(VisualDefinition->MaterialPath);
					if (UMaterialInterface* Material = LoadObject<UMaterialInterface>(nullptr, *MaterialObjectPath))
					{
						const int32 MaterialSlotCount = FMath::Max(StaticMesh->GetStaticMaterials().Num(), 1);
						for (int32 MaterialIndex = 0; MaterialIndex < MaterialSlotCount; ++MaterialIndex)
						{
							VisualTemplate->SetMaterial(MaterialIndex, Material);
						}
					}
					else
					{
						UE_LOG(LogCadImporter, Warning, TEXT("Failed to load material override for link %s visual %d: %s"), *Link.Name, VisualIndex, *VisualDefinition->MaterialPath);
					}
				}

				// Only the primary visual per link is used as the physics body.
				// Base primary stays kinematic to act as a stable world reference.
				// Constraints can still be created in fixed_assembly for topology/debug visualization.
				VisualTemplate->SetSimulatePhysics(bIsPrimaryVisual && !bIsBaseLink && !bIsFixedAssembly);
			}

			const FName VisualComponentName = VisualNode->GetVariableName();
			FTransform LinkRelativeVisualTransform = RelativeVisualTransform;
			if (VisualDefinition)
			{
				LinkRelativeVisualTransform = VisualDefinition->Transform;
			}
			else if (bAttachUnderPrimaryVisual && PrimaryVisualDefinition)
			{
				LinkRelativeVisualTransform = RelativeVisualTransform * PrimaryVisualDefinition->Transform;
			}

			VisualComponentNamesByLink.FindOrAdd(Link.Name).Add(VisualComponentName);
			VisualTransformByComponentName.Add(VisualComponentName, LinkRelativeVisualTransform);
			VisualOwningLinkByComponentName.Add(VisualComponentName, Link.Name);
			if (bIsPrimaryVisual)
			{
				PrimaryVisualNodeByLink.Add(Link.Name, VisualNode);
				PrimaryVisualIndexByLink.Add(Link.Name, VisualIndex);
				(*LinkNodePtr)->AddChildNode(VisualNode);
			}
			else if (USCS_Node** PrimaryVisualNode = PrimaryVisualNodeByLink.Find(Link.Name))
			{
				(*PrimaryVisualNode)->AddChildNode(VisualNode);
			}
			else
			{
				// Fallback in case a link has an unexpected visual order.
				(*LinkNodePtr)->AddChildNode(VisualNode);
			}
		}
	}

	if (bIsFixedAssembly)
	{
		// Static assemblies do not create physics constraints or joint drive settings.
		// Link hierarchy and transforms are still assembled via link/joint transform mapping.
		return true;
	}

	int32 WorldAnchorFallbackCount = 0;
	if (!BuildJointConstraintComponents(
		SCS,
		Model,
		BaseLinkName,
		LinkNodeByName,
		LinkTransformByName,
		RelativeTransformByChild,
		VisualComponentNamesByLink,
		VisualTransformByComponentName,
		VisualOwningLinkByComponentName,
		WorldAnchorFallbackCount,
		OutError))
	{
		return false;
	}

	if (WorldAnchorFallbackCount > 0)
	{
		FMessageDialog::Open(
			EAppMsgType::Ok,
			FText::FromString(FString::Printf(
				TEXT("Root link '%s' has no visual mesh.\nImported %d joint(s) using world-fixed anchor for component_name1.\nPlease verify the source JSON root visuals."),
				*BaseLinkName,
				WorldAnchorFallbackCount)));
	}

	// Base link is treated as a kinematic reference (physics disabled on its primary visual), so no world anchor constraint is created.

	return true;
}
